### ISSUE TITLE
req: way to disable dev tools on windows app?

### ISSUE THREAD

**Issue by Bhavukarora03** [jakky1/webview_win_floating#15]

**Comment by jakky1** [comment]
Fixed.

Please pull the latest code from github:
```
dependencies:
  webview_win_floating:
    git:
      url: https://github.com/jakky1/webview_win_floating.git
      ref: master
```
